### ISSUE TITLE
If organization isn't passed as in input the workflow fails

### ISSUE THREAD

**Issue by nedbat** [tspascoal/get-user-teams-membership#5]
We've been using this action for a while, but I just tried to convert one of our actions to a reusable action, and got this error:
```
Run tspascoal/get-user-teams-membership@v1.0.1
  with:
    username: cmltaWt0
    GITHUB_TOKEN: ***
ReferenceError: context is not defined
    at run (/home/runner/work/_actions/tspascoal/get-user-teams-membership/v1.0.1/dist/index.js:1:105323)
    at Object.351 (/home/runner/work/_actions/tspascoal/get-user-teams-membership/v1.0.1/dist/index.js:1:105188)
    at __webpack_require__ (/home/runner/work/_actions/tspascoal/get-user-teams-membership/v1.0.1/dist/index.js:1:107309)
    at /home/runner/work/_actions/tspascoal/get-user-teams-membership/v1.0.1/dist/index.js:1:107474
    at Object.<anonymous> (/home/runner/work/_actions/tspascoal/get-user-teams-membership/v1.0.1/dist/index.js:1:107500)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
Error: context is not defined
```
This could be my error somehow, but I've converted other workflows to be reusable, so I'm not sure what's different here.

Here is the failing action run:  https://github.com/openedx/devstack/runs/4857946347?check_suite_focus=true

Here's the pull request making the workflow reusable: https://github.com/openedx/.github/pull/6

**Comment by tspascoal** [comment]
@nedbat Sorry for the problem you are having.

I did a cursory look at your reusable workflow and can't find anything wrong with it, it should just work.

Specially since you are passing the organization, I will try to diagnose this on the weekend.

**Comment by tspascoal** [comment]
Hi @nedbat I have fixed the issue, my guess is that the secrets `CC_TEAM_CONTRIBUTORS_ORG` isn't defined. So if organization it is not passed as a parameter, it will use the organization of the caler workflow. If you intention is to use a secret is to reference  another organization it wouldn't work either, otherwise just skip the parameter or use `${{ github.repository_owner }}` to reference the caller organization to spare a secret

**Comment by markcmiller86** [comment]
I am running into what I think is a similar problem. I creaeted a *personal* (not org) Personal Access Token. The workflow works fine for an *issue* contributed by wholly external user but does not work for a pr...

* success for issue here, https://github.com/betterscientificsoftware/bssw.io/actions/runs/4758360292/jobs/8456320369
* failure for pr here, https://github.com/betterscientificsoftware/bssw.io/actions/runs/4767748401/jobs/8476351185

Again, I created the PAT in my own personal account, not the associated rep or org. Should I have done there?

**Comment by tspascoal** [comment]
@markcmiller86 [The PR job ](https://github.com/betterscientificsoftware/bssw.io/actions/runs/4767748401/jobs/8476351185)is failing, because secrets are not available in pull requests (the hint is the error that GITHUB_TOKEN parameter is empty) created from a fork ([see](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)) 
That is visible on the logs (notice `Secret Source: None` , it would show `Actions` otherwise like visible in the sucessful job )

![image](https://user-images.githubusercontent.com/7847935/233989584-56e3b370-63bd-463b-a8cf-4929a415775b.png)

The only way I am aware (I maybe be missing a simpler method) is to decouple the notification and be triggered on a `workflow_run` event when another WF completes (but then you might not have access to the PR/Issue)

As for using a PAT , you did good. (classic ) PATs always belong to a user not to an organization

**Comment by markcmiller86** [comment]
@tspascoal ok, thanks for taking a look and sharing that ref. I guess I hadn't dug deep enough in to GHA documentation.

**Comment by markcmiller86** [comment]
FYI...it looks like simply switching the trigger from `pull_request` to `pull_request_target` fixed it for me.
